# Define a series of nodes to use as a test bed

N = 1

Vagrant.configure("2") do |config|

  (1..N).each do |i|

    config.vm.define "node-#{i}" do |node|

      # Ubuntu 16.04
      node.vm.box = "ubuntu/xenial64"

      # Enable an internet connection
      node.vm.network "private_network", ip: "192.168.69.#{i+50}"
      
      # Enable shared folder
      node.vm.synced_folder ".", "/vagrant"

    end

  end  

end