---
- name: remove stack
  hosts: manager[0]
  become: yes
  tasks:
    - name: remove stack
      command: docker stack rm the-stack
      ignore_errors: yes

- name: remove all docker containers and images
  hosts: all
  become: yes
  tasks: 
    - name: remove all docker containers and images
      shell: |
        sudo docker kill $(sudo docker ps -q)
        sudo docker rm -f $(sudo docker ps -a -q)
        sudo docker rmi -f $(sudo docker images -q)
      ignore_errors: yes