---
- name: upload docker compose
  hosts: manager[0]
  become: yes
  tasks:
    - name: copy over docker compose
      copy:
        src: docker-compose
        dest: /home/appdev/deploy

- hosts: all
  become: yes
  tasks:
    - name: copy over registry tls certificate
      copy:
        src: domain.crt
        dest: /etc/docker/certs.d/104.236.60.90:443/ca.crt
    # - name: copy over registry tls certificate again
    #   copy:
    #     src: domain.crt
    #     dest: /usr/local/share/ca-certificates/104.236.60.90.crt
    # - name: update the ubuntu trusted certificates
    #   command: update-ca-certificates